"""Asset Radar project adapter.

Parses spec docs generated by the `spec-writing` skill (10-section skeleton,
markdown tables, Gherkin Scenario / Scenario Outline markers).
"""

from __future__ import annotations

import re
from pathlib import Path

from markdown_it import MarkdownIt
from markdown_it.tree import SyntaxTreeNode

from drift_check.adapters.base import (
    BugSpec,
    ChangelogRow,
    CodeTarget,
    FieldSpec,
    SpecLocation,
    TaskState,
)


# ---------------------------------------------------------------------------
# Section parsers (markdown-it-py based)
# ---------------------------------------------------------------------------

_MD = MarkdownIt("commonmark", {"html": False}).enable("table")


def _iter_tables(node: SyntaxTreeNode) -> list[SyntaxTreeNode]:
    """Yield all table nodes in the syntax tree."""
    return [n for n in node.children if n.type == "table"] if node.children else []


def _iter_tables_with_section(node: SyntaxTreeNode, section: str = "") -> list[tuple[str, SyntaxTreeNode]]:
    """Yield (current_section_heading, table_node) pairs.

    Tracks the most recent heading node seen in DFS, where SyntaxTreeNode
    headings have type="heading" with an "inline" child carrying the title.

    Implementation note: iterates top-down tracking the most recently seen
    heading text. Each root-level child recurses with the *current* heading
    context, not the parent's empty section.
    """
    out: list[tuple[str, SyntaxTreeNode]] = []
    cur = section
    for child in node.children or []:
        if child.type == "heading":
            for c in child.children or []:
                if c.type == "inline":
                    cur = _inline_text(c).strip()
                    break
        out.append((cur, child))
        if child.children:
            out.extend(_iter_tables_with_section(child, cur))
    return out


def _flatten_with_section(node: SyntaxTreeNode, section: str) -> list[tuple[str, SyntaxTreeNode]]:
    """DFS flatten with current heading section tracked.

    At each step, if we hit a heading node, update the current section from
    the heading's inline child text. Then recurse into children.
    """
    cur = section
    if node.type == "heading":
        for c in node.children or []:
            if c.type == "inline":
                cur = _inline_text(c).strip()
                break
    out: list[tuple[str, SyntaxTreeNode]] = [(cur, node)]
    for child in node.children or []:
        out.extend(_flatten_with_section(child, cur))
    return out


def _inline_text(node: SyntaxTreeNode) -> str:
    """Extract concatenated text from an inline node (text children only)."""
    if node.type != "inline":
        return ""
    parts: list[str] = []
    for child in node.children or []:
        if child.type == "text":
            parts.append(getattr(child, "content", "") or "")
        elif child.children:
            parts.append(_inline_text(child))
    return "".join(parts)


def _section_kind(section_heading: str) -> str:
    """Classify a markdown section heading as 'class' / 'field' / None.

    - 'class' for §2 术语表 / §2.1 / §2.2 etc.
    - 'field' for §4 数据模型 / §4.1 / §4.2 etc.
    - 'unknown' otherwise.
    """
    s = section_heading.lower()
    if re.match(r"§?\s*2(\.|\b)", s) or "术语" in s:
        return "class"
    if re.match(r"§?\s*4(\.|\b)", s) or "数据模型" in s or "字段表" in s:
        return "field"
    return "unknown"


def _table_to_rows(table: SyntaxTreeNode) -> list[list[str]]:
    """Convert a markdown-it table node to a list of cell-text rows."""
    rows: list[list[str]] = []
    for child in table.children or []:
        if child.type == "thead":
            for tr in child.children or []:
                rows.append([_cell_text(c) for c in (tr.children or [])])
        elif child.type == "tbody":
            for tr in child.children or []:
                rows.append([_cell_text(c) for c in (tr.children or [])])
    return rows


def _cell_text(cell: SyntaxTreeNode) -> str:
    """Extract plain text from a th/td cell."""
    return "".join(
        token.content for token in (cell.children or []) if getattr(token, "content", "")
    ).strip()


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------


class AssetRadarAdapter:
    """Adapter for the Asset Radar project (`.trae/specs/*`)."""

    SPECS_ROOT = Path(".trae") / "specs"
    LESSON_FILE = Path(".trae") / "rules" / "lessons-learned.md"
    DECISION_LOG = Path("决策日志.md")
    PROTOCOL_FILE = Path("src") / "asset_radar" / "protocol.py"

    # Per v8 decision + lessons-learned.md header (第 19 行「§1-§13 是早期项目
    # 内具体提醒，不通用」). spec.md / AGENTS.md / decision log may still reference
    # these for historical reasons — D5 detector must NOT flag them as dangling.
    HISTORICAL_LESSON_ANCHORS: frozenset[str] = frozenset(
        str(i) for i in range(1, 14)
    )  # {"1", "2", ..., "13"}

    def __init__(self, project_root: Path) -> None:
        self._root = Path(project_root).resolve()

    # --- identity ---

    def project_name(self) -> str:
        return "asset-radar"

    def project_root(self) -> Path:
        return self._root

    def lesson_refs_file(self) -> Path:
        return self._root / self.LESSON_FILE

    def decision_log_file(self) -> Path | None:
        p = self._root / self.DECISION_LOG
        return p if p.exists() else None

    # --- listing ---

    def list_specs(self) -> list[SpecLocation]:
        out: list[SpecLocation] = []
        root = self._root / self.SPECS_ROOT
        if not root.exists():
            return out
        for spec_md in sorted(root.glob("**/spec.md")):
            spec_dir = spec_md.parent
            # Exclude bug sub-specs — they are listed via list_bug_specs(),
            # not list_specs(). Otherwise they pollute the D1-D4 detectors
            # AND break D6 parent-resolution (since bug rel_spec_id doesn't
            # start with spec-XX).
            if spec_dir.relative_to(root).parts[0] == "bug":
                continue
            tasks_md = spec_dir / "tasks.md"
            checklist_md = spec_dir / "checklist.md"
            if not (tasks_md.exists() and checklist_md.exists()):
                continue
            rel = spec_dir.relative_to(root).as_posix()
            out.append(
                SpecLocation(
                    spec_dir=spec_dir,
                    spec_md=spec_md,
                    tasks_md=tasks_md,
                    checklist_md=checklist_md,
                    rel_spec_id=rel,
                )
            )
        return out

    def list_bug_specs(self) -> list[BugSpec]:
        out: list[BugSpec] = []
        bug_root = self._root / self.SPECS_ROOT / "bug"
        if not bug_root.exists():
            return out
        for spec_md in sorted(bug_root.glob("*/spec.md")):
            slug = spec_md.parent.name
            out.append(
                BugSpec(
                    spec_dir=spec_md.parent,
                    spec_md=spec_md,
                    slug=slug,
                    rel_path=spec_md.relative_to(self._root).as_posix(),
                )
            )
        return out

    def list_code_targets(self) -> list[CodeTarget]:
        """Return CodeTarget entries for every .py under src/asset_radar/.

        v92: expanded from protocol.py only to the entire src/asset_radar/
        tree so D2a can match every CamelCase class declared in any spec
        §2 table. Each module file gets a CodeTarget with class_names
        populated by AST scan of `class X:` / `class X(BaseModel):` /
        `class X(Protocol):` declarations.
        """
        import ast

        out: list[CodeTarget] = []
        src_roots = [
            self._root / "src" / "asset_radar",
            self._root / "src" / "ai_worker",
        ]
        for src_root in src_roots:
            if not src_root.exists():
                continue
            for py_path in sorted(src_root.rglob("*.py")):
                if py_path.name == "__init__.py":
                    continue
                try:
                    tree = ast.parse(py_path.read_text(encoding="utf-8"), filename=str(py_path))
                except SyntaxError:
                    continue
                class_names: list[str] = []
                for node in ast.walk(tree):
                    if isinstance(node, ast.ClassDef):
                        class_names.append(node.name)
                rel = py_path.relative_to(self._root).as_posix()
                layer = rel.split("/", 2)[1] if rel.count("/") >= 2 else "asset_radar"
                out.append(
                    CodeTarget(
                        py_path=py_path,
                        rel_path=rel,
                        layer=layer,
                        class_names=class_names,
                    )
                )
        # Keep legacy protocol.py entry pointing to PROTOCOL_FILE for callers
        # that hardcode it (D2b field compare).
        proto = self._root / self.PROTOCOL_FILE
        if proto.exists() and not any(t.py_path == proto for t in out):
            out.insert(
                0,
                CodeTarget(
                    py_path=proto,
                    rel_path=proto.relative_to(self._root).as_posix(),
                    layer="protocol",
                    class_names=[
                        "Platform",
                        "TaskConfig",
                        "Task",
                        "ImageMeta",
                        "ProductMeta",
                        "TaskResult",
                        "TaskError",
                        "WSMessage",
                        "AntiBotConfig",
                        "TaskStatus",
                        "ImageType",
                    ],
                ),
            )
        return out

    def list_all_class_names(self) -> list[str]:
        """AST-scan every .py under src/asset_radar/ and src/ai_worker/, return all class names.

        v92: added so D2a can match every CamelCase class declared in any spec
        §2 table (not just BaseModel in protocol.py). v208: expanded to also
        scan src/ai_worker/ so spec-05 class tables (LLMClient / WanxiangClient
        / TaskQueue / ImageStorage / MiniMaxClient / QueueManager / RateLimiter
        / RedisTaskQueue) match against code-side class declarations.

        v208: also scans frontend/sdk/ for ES6 `export class X` / `class X`
        declarations so spec-02 cross-layer JS anchors (PlatformAdapter /
        WSClient / EtsyAdapter / AmazonAdapter / ImageDownloader /
        RobotsChecker / Throttler / AdapterRegistry) match against code-side
        JS class declarations. Returns a deduplicated list sorted by first
        appearance.
        """
        import ast
        import re

        names: list[str] = []
        seen: set[str] = set()

        # Python source roots (AST scan)
        py_roots = [
            self._root / "src" / "asset_radar",
            self._root / "src" / "ai_worker",
        ]
        for src_root in py_roots:
            if not src_root.exists():
                continue
            for py_path in sorted(src_root.rglob("*.py")):
                if py_path.name == "__init__.py":
                    continue
                try:
                    tree = ast.parse(py_path.read_text(encoding="utf-8"), filename=str(py_path))
                except SyntaxError:
                    continue
                for node in ast.walk(tree):
                    if isinstance(node, ast.ClassDef) and node.name not in seen:
                        seen.add(node.name)
                        names.append(node.name)

        # JS source roots (regex scan for ES6 class + const object literals)
        js_root = self._root / "frontend" / "sdk"
        if js_root.exists():
            # v208: ES6 `export class X` / `class X` declarations.
            # v211: extend to ES6 `const X = {...}` / `let X = {...}` object
            # literals — AdapterRegistry (frontend/sdk/platforms/registry.js)
            # and similar const-object "service-like" identifiers need to be
            # matched against spec §2 rows so D2a doesn't false-positive on
            # them. Real-data scan: scripts/_tmp/verify_d2a_real_20260730.py
            # confirmed AdapterRegistry / RedactedConsole live as `const X =`
            # rather than `class X` declarations.
            js_class_re = re.compile(r"^(?:export\s+)?class\s+([A-Za-z_]\w*)")
            # v211 fix: const AdapterRegistry = new Map() — the rhs is a
            # constructor call (new Map), not a { or [ literal. Loosen
            # regex to match any `= <anything>` rhs.
            js_const_re = re.compile(r"^(?:export\s+)?(?:const|let|var)\s+([A-Za-z_]\w*)\s*=")
            for js_path in sorted(js_root.rglob("*.js")):
                try:
                    content = js_path.read_text(encoding="utf-8")
                except OSError:
                    continue
                for line in content.splitlines():
                    stripped = line.lstrip()
                    for pat in (js_class_re, js_const_re):
                        m = pat.match(stripped)
                        if m and m.group(1) not in seen:
                            seen.add(m.group(1))
                            names.append(m.group(1))
                            break

        return names

    # --- parsers ---

    def parse_version(self, md_text: str) -> str:
        """Extract version like `v1.0.0` from the first metadata block.

        Looks for `**版本:** vX.Y.Z` or `> **版本:** vX.Y.Z` first; falls back
        to `版本:` keyword; returns "unknown" if not found.
        """
        for pattern in (
            r"\*\*版本[:：]\*\*\s*(v\d+(?:\.\d+){0,2})",
            r"\*\*版本[:：]\*\*\s*(V\d+(?:\.\d+){0,2})",
            r"\*\*版本[:：]\*\*\s*(\d+(?:\.\d+){1,2})",
            r"版本[:：]\s*(v\d+(?:\.\d+){0,2})",
            r"版本[:：]\s*(V\d+(?:\.\d+){0,2})",
            r"版本[:：]\s*(\d+(?:\.\d+){1,2})",
            r"Version[:：]\s*(v\d+(?:\.\d+){0,2})",
        ):
            m = re.search(pattern, md_text)
            if m:
                return m.group(1)
        return "unknown"

    def parse_field_table(self, md_text: str) -> list[FieldSpec]:
        """Parse `§2 术语表` and `§4 数据模型` tables into FieldSpec.

        Each FieldSpec has `source_section` set to the current heading text.
        Callers (D2a / D2b) should use that to filter.

        Heuristic: keep rows where column 0 looks like an identifier AND
        there's a `类型` column somewhere.
        """
        tree = SyntaxTreeNode(_MD.parse(md_text))
        results: list[FieldSpec] = []

        for section_heading, table in _iter_tables_with_section(tree):
            rows = _table_to_rows(table)
            if len(rows) < 2:
                continue
            header = rows[0]
            # find column indices
            col_name = -1
            # Priority: English column name (English名) > name > 字段 > 字段名 > 术语.
            # The English column carries the actual code identifier (e.g. "Platform"),
            # while the 中文术语 column carries human-readable terminology. Drift-check
            # needs the code identifier to compare with BaseModel.__annotations__.
            for candidate in ("英文名", "name", "字段", "字段名", "术语"):
                for i, h in enumerate(header):
                    if h == candidate:
                        col_name = i
                        break
                if col_name >= 0:
                    break
            try:
                col_type = next(i for i, h in enumerate(header) if h in ("类型", "type"))
            except StopIteration:
                continue
            if col_name < 0:
                continue
            # v211: extract `代码映射` column index (optional — many spec
            # tables don't have this column; D2a detector's code_map
            # whitelist uses it to distinguish spec-concept rows from real
            # class rows). Priority order: 代码映射 > Code Map > code_map
            # > 映射 > mapping. Falls back to last column if none match.
            col_code_map = -1
            for candidate in ("代码映射", "Code Map", "code_map", "映射", "mapping"):
                for i, h in enumerate(header):
                    if h == candidate:
                        col_code_map = i
                        break
                if col_code_map >= 0:
                    break
            section_kind = _section_kind(section_heading)
            for row in rows[1:]:
                if len(row) <= max(col_name, col_type):
                    continue
                name = row[col_name].strip()
                ftype = row[col_type].strip()
                if not name or not ftype:
                    continue
                required = "Literal" not in ftype and "Optional" not in ftype
                # Extract code_map value; fall back to last column if
                # no explicit code_map column header matched.
                if col_code_map >= 0 and len(row) > col_code_map:
                    code_map = row[col_code_map].strip()
                else:
                    code_map = row[-1].strip() if row else ""
                results.append(
                    FieldSpec(
                        name=name,
                        field_type=ftype,
                        required=required,
                        default=None,
                        source_section=f"{section_heading} | kind={section_kind}",
                        code_map=code_map,
                    )
                )
        return results

    def parse_gherkin_count(self, md_text: str) -> int:
        """Count Gherkin Scenario / Scenario Outline blocks."""
        return len(
            re.findall(r"^\s*(?:Scenario(?:\s+Outline)?|场景|场景大纲)[:：]", md_text, re.MULTILINE)
        )

    def parse_task_states(self, md_text: str) -> list[TaskState]:
        """Parse tasks.md into TaskState list.

        Matches `⏳ T-XX ...` / `✅ T-XX ...` (also `T-` or `TC-` prefixes).
        Only the FIRST task ID on each line is treated as the task being
        defined; IDs appearing later (e.g. in dependency mentions like
        ``（依赖 sub-01 T-02-01）``) are ignored.
        """
        _TASK_ID_PATTERNS = (
            r"T-(?:sub|bug)?\d{2}-\d{2}",
            r"T-\d{2}-\d{2}",
            r"TC-[A-Za-z0-9_-]+",
        )
        out: list[TaskState] = []
        for line in md_text.splitlines():
            stripped = line.lstrip()
            if not stripped:
                continue
            state = None
            if "✅" in stripped or "[x]" in stripped.lower():
                state = "done"
            elif "⏳" in stripped or "[-]" in stripped.lower():
                state = "pending"
            elif "🔄" in stripped or "[~]" in stripped.lower():
                state = "in_progress"
            if state is None:
                continue
            content = re.sub(r"^[⏳✅🔄\s*|]+", "", stripped)
            m = None
            for pat in _TASK_ID_PATTERNS:
                m = re.match(pat, content)
                if m:
                    break
            if not m:
                continue
            out.append(TaskState(task_id=m.group(0), state=state, code_target=None))
        return out

    def parse_task_code_target(self, task_id: str, tasks_md: str, spec_md_path: Path | None = None) -> CodeTarget | None:
        r"""Resolve a task id to the code file it describes (best-effort).

        Returns CodeTarget even if the file does NOT exist — the detector
        (D4) needs the declared path to flag a phantom_done drift.

        Accepts paths under: src/, frontend/, tests/, cli/, scripts/.

        v92: if task line has no code path, fallback to spec.md header's
        「代码目标」 field (e.g. ``> **代码目标:** `src/asset_radar/protocol.py::Platform```).
        """
        roots = ("src", "frontend", "tests", "cli", "scripts")
        pattern = (
            r"((?:" + "|".join(roots) + r")/[A-Za-z0-9_./-]+\.(?:py|js|ts|html))"
        )
        for line in tasks_md.splitlines():
            if task_id not in line:
                continue
            m = re.search(pattern, line)
            if m:
                py = self._root / m.group(1)
                return CodeTarget(
                    py_path=py,
                    rel_path=m.group(1),
                    layer="auto",
                    class_names=[],
                )

        if spec_md_path and spec_md_path.exists():
            spec_text = spec_md_path.read_text(encoding="utf-8")
            code_target_match = re.search(r"> \*\*代码目标[:：]\*\* `([^`]+)`", spec_text)
            if code_target_match:
                code_path = code_target_match.group(1).split("::")[0]
                py = self._root / code_path
                if py.exists():
                    return CodeTarget(
                        py_path=py,
                        rel_path=code_path,
                        layer="auto",
                        class_names=[],
                    )
        return None

    def parse_lesson_refs(self, md_text: str) -> list[str]:
        """Find all `§XX` references in markdown text.

        Returns only refs preceded by the keyword `lessons` (case-insensitive),
        within the same line. This filters out spec.md internal section numbers
        (§0 / §1 / §2 ...) and soul.md internal navigation (§3.4 / §6.2 ...).
        """
        # Look for `lessons` keyword within 50 chars BEFORE §XX on the same line
        pattern = re.compile(
            r"lessons?[^§\n]{0,50}§(\d+[a-z]?)", re.IGNORECASE
        )
        refs = pattern.findall(md_text)
        # dedupe preserve order
        seen: set[str] = set()
        out: list[str] = []
        for r in refs:
            if r not in seen:
                seen.add(r)
                out.append(r)
        return out

    def parse_parent_spec(self, bug_slug: str) -> str | None:
        """A bug sub-spec may have a header like `父 spec: spec-02-runner/sub-08-...`.

        We scan all bug spec.md files for this slug and extract the parent hint.
        """
        bug_root = self._root / self.SPECS_ROOT / "bug"
        if not bug_root.exists():
            return None
        for spec_md in bug_root.glob("*/spec.md"):
            if spec_md.parent.name != bug_slug:
                continue
            text = spec_md.read_text(encoding="utf-8")
            m = re.search(r"父\s*spec[:：]\s*([^\n]+)", text)
            if m:
                return m.group(1).strip()
            # fallback: derive from spec-00 / spec-01 / spec-02 mention
            for spec_id in ("spec-00", "spec-01", "spec-02", "spec-03", "spec-04"):
                if spec_id in text:
                    return spec_id
        return None

    def historical_lesson_anchors(self) -> set[str]:
        """Per v8 decision: §1-§13 are deprecated, kept as historical anchors.

        References to these from spec.md / AGENTS.md / decision log are
        intentional (the spec was written when those lessons were live).
        D5 must not flag them as dangling — D5 should silent skip them.
        """
        return set(self.HISTORICAL_LESSON_ANCHORS)

    def parse_changelog_table(self, spec_md: str) -> list[ChangelogRow]:
        """Parse §9.5 changelog table (or near the end of spec.md)."""
        tree = SyntaxTreeNode(_MD.parse(spec_md))
        rows: list[ChangelogRow] = []
        for table in _iter_tables(tree):
            trows = _table_to_rows(table)
            if not trows:
                continue
            header = trows[0]
            # detect changelog columns
            if not any("版本" in h or "Version" in h for h in header):
                continue
            try:
                col_ver = next(i for i, h in enumerate(header) if "版本" in h or "Version" in h.lower())
            except StopIteration:
                continue
            col_date = next((i for i, h in enumerate(header) if "日期" in h or "Date" in h.lower()), -1)
            col_sum = next(
                (i for i, h in enumerate(header) if "变更" in h or "摘要" in h or "summary" in h.lower()),
                -1,
            )
            for row in trows[1:]:
                if len(row) <= col_ver:
                    continue
                ver = row[col_ver].strip()
                date = row[col_date].strip() if col_date >= 0 and col_date < len(row) else ""
                summary = row[col_sum].strip() if col_sum >= 0 and col_sum < len(row) else ""
                if not ver:
                    continue
                rows.append(ChangelogRow(version=ver, date=date, summary=summary))
        return rows